dataset: "AISHELL3"

path:
  corpus_path: "../Dataset/AISHELL-3"
  lexicon_path: "lexicon/pinyin-lexicon-r.txt"
  raw_path: "./raw_data/AISHELL3"
  preprocessed_path: "./preprocessed_data/AISHELL3"

preprocessing:
  speaker_embedder: "DeepSpeaker" # support 'none', 'DeepSpeaker'
  speaker_embedder_cuda: False # since it's too large to load in a single GPU

#  target_speakers: ["SSB0009", "SSB0760", "SSB1563", "SSB0033", "SSB0307", "SSB1891", "SSB1878", "SSB0043", "SSB0534", "SSB0686", "SSB1365", "SSB0273", "SSB1863", "SSB1831", "SSB0631", "SSB1328", "SSB1100", "SSB0241", "SSB0966", "SSB0073",]
  val_size: 512
  text:
    text_cleaners: []
    language: "zh"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  duration:
    beta_binomial_scaling_factor: 1.0
