seed: 8000
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "./output/ckpt/Gradient-Reversal-CrossLingual-Data-50-50-weight0_02"
  log_path: "./output/log/Gradient-Reversal-CrossLingual-Data-50-50-weight0_02"
  result_path: "./output/result/Gradient-Reversal-CrossLingual-Data-50-50-weight0_02"
optimizer:
  batch_size: 2 #16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 4
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000 #1000
  val_step: 1000 # 1000
  save_step: 50000
duration:
  binarization_start_steps: 6000
  binarization_loss_enable_steps: 18000
  binarization_loss_warmup_steps: 10000
