seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "./output/ckpt/LibriTTS-VAE-Finetune"
  log_path: "./output/log/LibriTTS-VAE-Finetune"
  result_path: "./output/result/LibriTTS-VAE-Finetune"
optimizer:
  batch_size: 16 #16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 4
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000 # 1000
  save_step: 100000 #25000
duration:
  binarization_start_steps: 6000
  binarization_loss_enable_steps: 18000
  binarization_loss_warmup_steps: 10000

vae:
  vae_start_steps: 300000
  kld_loss_enable_steps: 310000
  kld_loss_warmup_steps: 10000
  kld_final_weight: 0.001
  org_embed_rate: 0.2
